version: '3.8'
services:
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_DB: laba3_web
      POSTGRES_PASSWORD: Qwerty123
  jsf-web-lab3-application:
    container_name: jsf-web-lab3-application
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - postgres-db
